### ISSUE TITLE
Standardize colors for elements

### ISSUE THREAD

**Issue by nesl247** [dracula/dracula-theme#192]
Elements such as line numbers, the line number gutter, cursor, etc. should all have an official list of colors. It would also be help to have a preferred color for function names, class names, etc.

If an editor doesn't have the ability to choose the correct color, we'll have to deal with it (for instance PhpStorm is a bit weak when it comes to coloring specific tokens separately), however this will allow us to get as close as possible.

Once we have a full list, the current color palette will be renamed to "Base Color Palette" or something of the sort, with a new file linked in the README for a full color palette used for editors and IDEs.

Elements:

| Element | Hex | RGB | HSL |
| --- | --- | --- | --- |
| Line numbers |  |  |  |
| Line number gutter |  |  |  |
| Cursor |  |  |  |
| Code warnings |  |  |  |
| Code errors |  |  |  |
| *Doc Tags (eg. PhpDoc, JDoc) |  |  |  |
| Class name |  |  |  |
| Function name |  |  |  |
| Function visibility |  |  |  |

If more elements are thought of I will add them to this list.

**Comment by hackwaly** [comment]
Request to add slight color element for highlight delimiters.
* Delimiters of structured literal: `{` `}` `[` `]` `,`
* OCaml quoted string `{xml|xml text|xml}`. It's better that highlight `{xml|` and `|xml}` in separated color.

I prefer using dark slight color for these to avoid distract users.

**Comment by ajitid** [comment]
Any update here? May 16 seems to be a long time 😕

**Comment by zenorocha** [comment]
No updates here @ajitid, this change will affect all 38 themes, feel free to send a proposal if you're interested on this topic.

**Comment by dsifford** [comment]
I'm interested in this topic. I'm going to start working on it (whenever time allows) here: https://github.com/dracula/visual-studio-code/issues/12

I think that rather than tackling this across all 38 repos simultaneously, the only way to reasonably do it is to start with one "champion" repo to show that it can, in fact, be done (and done well).

Once it's all done in a single repo and documented out, that single repo would then send in an RFC to the main dracula repo and a discussion can be started about the color choices. I would expect this discussion to last a few months at least so that everybody's thoughts and ideas could be captured.

Anyway, that's what I'll likely do when time allows. So if you're interested in chiming in with thoughts @ajitid, feel free to do so there.

**Comment by zenorocha** [comment]
Sounds like a great plan, thanks a lot @dsifford, you're rocking on the vscode theme! :metal:

**Comment by ajitid** [comment]
Thanks @dsifford!

**Comment by joaoevangelista** [comment]
Some elements that may be common to most of languages that we could add to the list:
- Strings
- Parameters
- Numbers

**Comment by dsifford** [comment]
Finished the initial specification and implementation this morning. Gonna clean some stuff up and then PR an RFC shortly.

**Comment by dsifford** [comment]
RFC here: https://github.com/dracula/dracula-theme/issues/232

**Comment by zenorocha** [comment]
Closing in favor of #232
