### ISSUE TITLE
Light theme

### ISSUE THREAD

**Issue by idoo** [dracula/dracula-theme#209]
It's a quite strange thing, but sometime, when I'm working on sun, my eyes want go away.
Does somebody have same issues? =)
I saw, that you're not planing to create a light theme, but may be somebody found a good alternative 😟 

![dracula-cris-from-horror-of-dracula](https://cloud.githubusercontent.com/assets/738921/20116887/324c0480-a60f-11e6-84c4-855e765999d7.jpg)

**Comment by zenorocha** [comment]
Hahahahaha that's a very good point. Unfortunately, we don't have enough resources to work on a light theme and support it in some many different platforms. But thanks a lot for bringing this up :)

**Comment by mbger** [comment]
SAD! Was looking forward to a van Helsing theme ;)
Thank you for the great work on the Dracula theme!

**Comment by zenorocha** [comment]
hehe I like the name :P

**Comment by faviobecker** [comment]
Yes, let's do it, I suggest we start by using the Brackets light theme as a basis :) - Van Helsing ftw 👍

**Comment by karosc** [comment]
seems like a fork of the vscode theme has [made an attempt](https://github.com/ashrafhadden/dracula.min)

**Comment by grippado** [comment]
hello @zenorocha hi from 2022, Im working at my new personal page, and using Dracula palette, and a single search, WHY DONT exists an "DracuLight" (only Brazilians with low IQ and "a Praça é Nossa" humor sense understad this "trocadilho") version??? why?? I felt challenged!!

**Comment by zenorocha** [comment]
@grippado I love that "Praça é Nossa" reference lol lol lol

Every now and then I think about creating a light theme, however, I still think it's not the right move at this point.
Here's why: https://github.com/dracula/dracula-theme/discussions/508#discussioncomment-319333

**Comment by Draculah** [comment]
Hello,

I am a programmer-student and found out about the Dracula theme when I had to switch from PyCharm to Visual Studio (due to a type actually; I didn't like the VS theming and instead wanted PyCharm's _darcula_ theme :p). I've been using the dracula theme everywhere as soon as I discovered it's very wide-spread (as there is support in [Stylus themes](https://userstyles.world/search?q=Dracula&sort=newest) for YouTube, StackOverflow, Github, ... or even in privacy alternative clients such as [libreddit](https://reddit.artemislena.eu/settings), hopefully [Invidious](https://yewtu.be/feed/popular) some day, ...), which is over 2 years now.

However, since restrictions on Covid ended, and I'm terrible at studying at home, I started a few months ago studying in the library. At home, I'm at a (quite) dark place when I'm working on my laptop. At the library (and basically any room in the university), there is quite a lot of light, and as well in the (2) businesses I've been in. A senior - those who usually never use dark themes - asked me why I was using a dark theme, and questioned if a light variant wouldn't be much more readable. ("I know better", I thought.) In an attempt to show them they are wrong, I switched to he light variant right away and surprised myself the light theme was actually much more readable _at reasonably lit places; definitely those by (in)direct sunlight_.

I can see a Dracula light theme become useful for people who have "auto dark/light theme" system settings based on the daylight; i.e. light theme from morning till the evening. It would of course be fantastic if applications themselves did not just allow "system dark/light" theme, but rather give you the option to chose _which light theme_ and _which dark theme_ to use for system themes.

We aren't there yet, and I feel such would take a while before it's as widely implemented as dark themes (if ever), but the first step for the Dracula theme would be to support a light variant of course. Defining a standard light color palette _that is readable_ still seems to need testing & tweaking, though I find the vscode light theme already a good attempt, (thanks @karosc!) and will test it myself where applicable during actual programming.

As I switched to Linux about half a year ago, I got to install the Dracula gtk theme. Now, I had found there is a [night theme switcher](https://extensions.gnome.org/extension/2236/night-theme-switcher/) for Gnome Desktop, so having a light variant for that would already be useful to have consistency between light and dark themes, instead of picking a random light theme with complete different styling for day time. (So, a use case already exists, for _1_ application.) On the other side, theming in gnome [is having some debate](https://www.omgubuntu.co.uk/2019/05/open-letter-stop-gtk-theming-distros) and may result in less theming possibilities - but I'm not following this evolution _that_ well.

I don't see any trend going to my dreamy world in which the theme would automatically switch in function of the amount of sunlight falling on it, but having a light theme available, still would give _me_ the opportunity to manually switch, which is what I do (for a few applications supporting default light/dark themes) when I'm in the library. I wonder if no-one else found themselves having a hard time reading in lit places :o Hopefully, at least, there will be enough need and resources for this to become a thing some day. Yes, maybe _I_ could start off with one, but I have so many things I myself want to finish as well and I have very little experience in theming either. Who knows! :)

In mean while; thanks for all the work in the themes <3
