### ISSUE TITLE
New Themes: PuTTY and ConEmu

### ISSUE THREAD

**Issue by teeli** [dracula/dracula-theme#214]
## New Theme

I've created themes for [PuTTY ](http://www.putty.org/)and [ConEmu ](https://conemu.github.io/)based on Dracula. Submitting them here, if you are interested in adding them.

PuTTY: https://github.com/teeli/dracula-putty
ConEmu: https://github.com/teeli/dracula-conemu

**Comment by zenorocha** [comment]
That's awesome @teeli!

We already have a ConEmu theme so if you could become a maintainer and contribute to the existing one, it would be great.

PuTTY will be an awesome addition!

I sent you an invitation to join the organization, let me know when you accept it.

**Comment by teeli** [comment]
Great, I accepted the invitation now :)

**Comment by zenorocha** [comment]
Great! Now you should be able to transfer the repository :)

**Comment by zenorocha** [comment]
Friendly ping :)

**Comment by teeli** [comment]
Actually I forgot about this completely and haven't really been maintaining my stuff (shame on me). Check the repository link in my first message, it should still work. Actually now that there's actually demand for this, I think I have to get active again.

**Comment by gkroon** [comment]
Hi all, I sent @teeli a pull request a week ago about a quick PowerShell import script I created for dracula-putty but I felt like creating my own fork (no offense!). Seems that my PuTTY settings are stored in the HKU registry hive, rather than his proposed HKCU registry hive (can anyone confirm HKU as well??). @teeli: If you still want the pull request, please reach out to me. If you no longer wish to maintain dracula-putty, I'd be happy to take over.

**Comment by teeli** [comment]
@gkroon I've been meaning to get back to this but life keeps getting in the way. I'm happy to hand over the project to you if you want.

**Comment by gkroon** [comment]
I'd be happy to take over then. :slightly_smiling_face:

**Comment by Diromns** [comment]
Is this no longer supported?

**Comment by bigpick** [comment]
The official [Dracula theme for ConEmu can be found here](https://github.com/dracula/conemu/tree/master); if there is still interest in the Putty versions and the original contributors above don't reply back / aren't interested in contributing their versions, I'll fork and clean them up to the standardized Dracula format and add them as a new theme myself (crediting appropriately).

If there's no longer interest/this isn't engaged in still after some time, I'd think we could close this as it's been around since 2017 and hasn't been very active at all.
