### ISSUE TITLE
Dracula for cmder

### ISSUE THREAD

**Issue by oguhpereira** [dracula/dracula-theme#274]
## New Theme?

I created dracula theme to cmder.
[dracula-cmder](https://github.com/oguhpereira/Dracula-cmder) is simar to [dracula-conemu](https://github.com/dracula/conemu).

![dracula-cmder](https://raw.githubusercontent.com/oguhpereira/Dracula-cmder/master/cmdericon.PNG)

This printscreen is the cmder in bash terminal and cmd terminal.

**Comment by hacknug** [comment]
Hey @oguhpereira :wave: Would you mind adding the _Team_ section to the readme? You can take a look at it on [the template](https://github.com/dracula/template). After this I think it'll be ready to be moved to the org. Let me know if/when it's done and I'll set the team and send you the invite! 👍

**Comment by oguhpereira** [comment]
@hacknug I updated my readme. When you move my repository to dracula and to add in website, I will change install.

**Comment by hacknug** [comment]
@oguhpereira just sent you the invite. Let me know once you've transferred the repo to the org so I can set the right permissions 👍 

Can't add the project to the website because there's no way to build the site as of now (one of the services it depended on shut down a while ago). Will try to rebuild it at some point in the near future tho.

**Comment by hacknug** [comment]
@oguhpereira it's you who have to transfer the repo to the organization. If you don't know how to do that, please read this article: https://help.github.com/en/articles/transferring-a-repository

**Comment by hacknug** [comment]
@oguhpereira repo renamed and permissions all set. Thank you so much for your contribution! :tada:
