### ISSUE TITLE
Dracula for CudaText

### ISSUE THREAD

**Issue by jackdp** [dracula/dracula-theme#275]
Hi Dracula Team!

I made Dracula theme for [CudaText](https://github.com/Alexey-T/CudaText) editor.

Repository
https://github.com/jackdp/Dracula-CudaText

Screenshot
![Screenshot](http://www.pazera-software.com/cudatext/themes/cudatext_dracula.png)

Installation
https://github.com/jackdp/Dracula-CudaText#install

**Comment by hacknug** [comment]
Hey @jackdp :wave: Just sent you an invitation to join the org. After accepting it, you can transfer the theme to the organization and I'll set the right permissions so you can push changes directly to it. Let me know if you have any questions about the process 👍

**Comment by zenorocha** [comment]
Friendly ping :)

**Comment by bigpick** [comment]
re-pinging @jackdp  again; no response here or https://github.com/jackdp/Dracula-CudaText/issues/3; if you're no longer interested in including the theme to the org/maintaining the theme, would you mind closing the issue here?
* If this is the case, are you particularly opposed to someone forking your repo/updating/contributing back in to the org themselves? 

---

Thanks!

**Comment by kazi-sifat-plus9a** [comment]
why it still not added.... 
i cant live without dracula theme

**Comment by luxonauta** [comment]
We seem to have been without answers for a while now 😢; I may be cloning the repository and adding the organization. Are you interested in continuing it @bigpick?
