### ISSUE TITLE
Question about using dracula theme on vim

### ISSUE THREAD

**Issue by KeunwooPark** [dracula/dracula-theme#286]
Hi.

I'm trying to use dracula theme with tmux and vim(7.2.1689).
I followed instruction on the webpage. I'm using Vim-plug.

However, the actual result doesn't seem right.
The left shows my sample python code, and the right image shows my vimrc.

![dracula](https://user-images.githubusercontent.com/1640277/43884181-61d8cb42-9bf0-11e8-9ebb-74d5ba7784ef.PNG)

Could anyone tell me what option I should add more on vimrc?

**Comment by wenindoubt** [comment]
On the left pane, can you run `:colorscheme` and confirm that it is using dracula?

It's also possible your VIM is unable to find the `dracula.vim` file since Vim-Plug installs the theme to `~/.local/share/nvim/plugged/dracula/colors/dracula.vim`

So basically, try this so your VIM can read your `dracula.vim` color file properly:

`ln -s ~/.local/share/nvim/plugged/dracula/colors/dracula.vim ~/.vim/colors`

**Comment by KeunwooPark** [comment]
I ran :colorscheme on the left pane, and it showed that I'm using dracula.

And I don't have 'nvim' directory. I'm using regular vim. 
But I found dracula.vim file in Vim-Plug. 
So I did "ln -s ~/.vim/plugged/dracula/colors/dracula.vim ~/.vim/colors"
But it didn't solve the problem.

**Comment by fakemonster** [comment]
try setting your TERM env variable to 256 colors: `export TERM=xterm-256color`. long term you can set that in your .bashrc

**Comment by KeunwooPark** [comment]
Thanks for the comment, but your solution did not work too. I added 'export TERM=xterm-256color' in .bashrc and .vimrc is same as the above image. And the output is also the same.

**Comment by zenorocha** [comment]
Issue moved to [dracula/vim #107](https://github.com/dracula/vim/issues/107) via [**ZenHub**](https://www.zenhub.com/)
