### ISSUE TITLE
comments hard to read when highlighted

### ISSUE THREAD

**Issue by bricerebsamen** [dracula/dracula-theme#318]
comments are very hard to read when highlighted (vim c++). See dracula/vim#95

### Screenshot
![selection_036](https://user-images.githubusercontent.com/1027398/41791568-efcefc70-760a-11e8-9239-a6d24c218bb8.png)

**Comment by bricerebsamen** [comment]
I really love dracula otherwise, but this has become too much of a pain point so I'm switching to jellybean for the time being

**Comment by ahnafalrafi** [comment]
I second this. For (neo)vim I have adjusted this by changing the highlight color for the current line in my init.vim to make it darker than the background (so that it is distinguishable from the background and allows for greater contrast against the colors for comments). I checked for the hex code for hsl(231, 15%, 12%) and it is #1a1b23 (the background has the same first two arguments, but it is 18% at the end). I made this the highlighting for the current line by including
`
highlight CursorLine cterm=NONE ctermbg=234 guibg=#1a1b23
`
in my init.vim **after** calling `syntax on`. It would be great though if something similar could be made default (with better color choices from those more visually adept than myself) - this solution is hacky at best, and doesn't improve legibility for comments across the board for other editors, only for (neo)vim!

**Comment by ahnafalrafi** [comment]
Oh the end result looks like this for me:
![Screenshot from 2019-06-23 16-36-30](https://user-images.githubusercontent.com/20092027/59982280-3ddd5980-95d5-11e9-969e-935749599efc.png)

**Comment by hacknug** [comment]
Agree this could/should be improved. Would like to hear other users opinion on the issue before we make any changes to the color palette 👍

**Comment by Shrek6** [comment]
I switched away from this theme because of this issue

**Comment by zx1986** [comment]
me too :-( @Shrek6

**Comment by benknoble** [comment]
Is there any forward progress on trying different values?
