### ISSUE TITLE
[Theme Request] Jupyter Lab

### ISSUE THREAD

**Issue by mzhukovs** [dracula/dracula-theme#348]
Jupyter Lab (the successor to Jupyter Notebooks), includes the ability to add custom themes to it (including via its extension manager, which just relies on npm packages - here is [an example of a Jupyter Lab theme extension package](https://github.com/oriolmirosa/jupyterlab_materialdarker)). Jupyter Lab supports python (of course), but also more recently [C# and F# notebooks](https://devblogs.microsoft.com/dotnet/net-core-with-juypter-notebooks-is-here-preview-1/). It would be very sweet to have an official Jupyter Lab Dracula theme. Pretty please :)

**Comment by zenorocha** [comment]
I just found this: https://github.com/karosc/jupyterlab_dracula.

@karosc would you be interested in moving this theme to the official organization?

**Comment by karosc** [comment]
Sure, although I have neglected the repo since the release of Jupyterlab Version 1.0.0. It works fine with the current version of JupyterLab, but may benefit with some more public use and contribution. Do you need anything from me to add to the org?

**Comment by zenorocha** [comment]
That's awesome! I just invited you to the org, so know all you have to do is:

* Accept GitHub invitation
* Transfer the repository
* Apply the same format used on https://github.com/dracula/template

The last step is important because it will be used to auto-generate the site. Especially the screenshot.png and INSTALL.md files.

Let me know if you have any questions

**Comment by karosc** [comment]
alright, should be [all set](https://github.com/dracula/JupyterLab).

**Comment by zenorocha** [comment]
It's live! Thanks @karosc ;)

https://draculatheme.com/jupyterlab
