### ISSUE TITLE
[New Theme] Fluent Terminal

### ISSUE THREAD

**Issue by vandreleal** [dracula/dracula-theme#358]
Dracula for Fluent Terminal
Repo: [https://github.com/vandreleal/dracula-fluent-terminal](https://github.com/vandreleal/dracula-fluent-terminal)

![screenshot](https://user-images.githubusercontent.com/9258892/70371079-2527de00-18ad-11ea-84a9-fa5432c8234b.png)

**Comment by zenorocha** [comment]
Hey @vandreleal, would you be interested on moving this theme to the official organization? You would still be the owner and maintainer, but the repo would live under https://github.com/dracula.

Let me know and I'll send further instructions.

**Comment by vandreleal** [comment]
Hey @zenorocha,
Yes, that sounds great. thank you!

**Comment by zenorocha** [comment]
That's awesome! I just invited you to the org, so know all you have to do is:
1. Accept GitHub invitation
2. Transfer the repository
3. Apply the same format used on https://github.com/dracula/template

The last step is important because it will be used to auto-generate the site. Especially the `screenshot.png` and `INSTALL.md` files.

Let me know if you have any questions

**Comment by vandreleal** [comment]
Thanks for the instructions, @zenorocha . Can you please take a look and let me know if everything looks good? [https://github.com/dracula/fluent-terminal](https://github.com/dracula/fluent-terminal)

**Comment by zenorocha** [comment]
It's live! https://draculatheme.com/fluent-terminal

Thanks @vandreleal!
