### ISSUE TITLE
New MATLAB theme

### ISSUE THREAD

**Issue by zenorocha** [dracula/dracula-theme#368]
https://github.com/scottclowe/matlab-schemer

**Comment by j-hap** [comment]
I have one ready to go, but I'm not sure where to put it. I could either make a PR to [](https://github.com/scottclowe/matlab-schemes) or you create dracula/matlab. Since one would need scott's schemer anyway, I think the scheme would reach more people if it's there.

**Comment by zenorocha** [comment]
Hey @j-hap, looks like this repo is not maintained for a long time, so I think it's better to create a dedicated dracula/matlab repo. Can you create a repo based on https://github.com/dracula/template?

**Comment by raghavmallampalli** [comment]
I was looking around for a MATLAB dracula theme and came across this thread. Since I don't have time to create a repo and I couldn't find the config file in the repos previously made I thought I'd share my config file and install method.

- Download the following file and unzip to a known location: [dracula.zip](https://github.com/dracula/dracula-theme/files/5052836/dracula.zip)
- Go to the Get Add-On window in MATLAB (HOME tab) and install the [MATLAB schemer by Scott Clowe](https://github.com/scottclowe/matlab-schemer).
- Type `schemer_import` at the command window, hit Enter a select the unzipped dracula.prf file.
- Restart MATLAB

Notes: 
- This does not change the color of the toolbar or view separators. MATLAB does not allow the color of these elements to be changed, unfortunately.
- To edit the color scheme, change the color in preferences as required and run `schemer_export` at the command window.

If anyone else wants to modify/use this file and create a repo with it please go ahead. You can just add my name in the contributors section.

**Comment by j-hap** [comment]
I finally came around to creating the repo as promised. It's here: https://github.com/j-hap/matlab and I already made all the links point to to the dracula website and project so it can be merged into https://github.com/dracula/. What do I do now?

**Comment by zenorocha** [comment]
That's awesome. Thanks for putting this together :) 

I just sent you an invitation to join the Dracula org. Once you accept the invite, you can transfer that repository.

**Comment by j-hap** [comment]
It's done. I tranferred it to https://github.com/dracula/matlab
