### ISSUE TITLE
A Dark theme for Discourse

### ISSUE THREAD

**Issue by jordanvidrine** [dracula/dracula-theme#381]
Hey there, I'm a designer over at [Discourse](https://www.discourse.org/). We create software that enables civilized discussion communities, teams, fans, and clubs.

I love using the Dracula theme in VScode for work, so I decided to create a Dracula dark theme for our users to be able to use for themselves.

Thanks so much for the work you do!

https://github.com/jordanvidrine/discourse-dracula-theme

**Comment by zenorocha** [comment]
That's amazing Jordan! Can you believe that a couple weeks ago I set up a Discourse instance and started working on something like this??? I ended up dropping the idea of using Discourse at that time, because of the price, but seeing this theme makes me very happy and excited about Discourse again :D

I just sent you an invitation to join the Dracula organization. Once you accept, can you transfer this repository?

Here are couple of changes we would need for the site:
* Rename repo from `discourse-dracula-theme` to `discourse`
* Rename file from `discourse-dracula.png` to `screenshot.png`
* Create a `INSTALL.md` to describe how to activate this theme

**Comment by jordanvidrine** [comment]
Ah that is so cool to hear that you set up and were trying Discourse out. Not sure what your purpose was behind the forum, but if it is for an open source project, we offer free hosting for that [here](https://blog.discourse.org/2018/11/free-hosting-for-open-source-v2/).

I'll go ahead and make these changes, accept the invite, and transfer the repo.

Thanks!

**Comment by zenorocha** [comment]
It's live! https://draculatheme.com/discourse

Thanks @jordanbrown, this is really exciting ;)

**Comment by jordanvidrine** [comment]
Looks awesome! So glad this got to happen
