### ISSUE TITLE
Dracula Ableton Live Theme

### ISSUE THREAD

**Issue by QuietImCoding** [dracula/dracula-theme#386]
## Dracula Theme for Ableton Live

Ableton Live is a really popular DAW, probably used by thousands of music producers. I figured it would be fun for them to have access to this one incredibly widely supported theme. This theme was built with [abletonthemes.com](https://www.abletonthemes.com), and you can remix it [here](https://www.abletonthemes.com/themes/dracula/8546) if you'd like.

[repo link](https://github.com/QuietImCoding/ableton-live)

**Comment by zenorocha** [comment]
That's awesome @QuietImCoding!

Would you be interested in transferring this repository to the official organization (https://github.com/dracula)? You'll continue maintaining this project, the only difference is that we can make it more visible and include it on the site (https://draculatheme.com).

What do you think? I sent you an invite :)

**Comment by QuietImCoding** [comment]
Hey! Sounds good 👍 
I'm working on transferring it now. Unfortunately I forked your template repo so I need to somehow unfork it before I can transfer the repository.

**Comment by zenorocha** [comment]
Hey @QuietImCoding, the theme is finally live!

https://draculatheme.com/ableton-live

I had to make some small adjustments in order to follow the same pattern as the other repositories, but other than that it looks amazing.

https://github.com/dracula/ableton-live/commit/c5c18246b557ccaa6bddd8940ff4fa0e5febdc60
