### ISSUE TITLE
[FR] Dracula for qbittorrent

### ISSUE THREAD

**Issue by zdmgmail** [dracula/dracula-theme#471]
hope a theme for https://github.com/qbittorrent/qBittorrent

**Comment by totoroot** [comment]
Since [qBittorent](https://github.com/qbittorrent/qBittorrent) is built with Qt you could use [Kvantum](https://github.com/tsujan/Kvantum/tree/master/Kvantum) to apply the [Dracula GTK theme](https://github.com/dracula/gtk) to all Qt applications.
This does not mean that I think this request is not valid, but I thought I propose this since this is how I got the Dracula theme applied to most of the Qt applications installed on my systems.

**Comment by MahdyMirzade** [comment]
https://github.com/dracula/dracula-theme/issues/576
I've did an awful theme here

**Comment by zenorocha** [comment]
It's live now thanks to @mahdymirzade!

https://draculatheme.com/qbittorrent
https://github.com/dracula/qbittorrent
