### ISSUE TITLE
Dracula theme for LiteIDE

### ISSUE THREAD

**Issue by SpikedPaladin** [dracula/dracula-theme#483]
### Screenshot
![Screenshot](https://raw.githubusercontent.com/SpikedPaladin/liteide/master/screenshot.png)

### Repository
[GitHub](https://github.com/SpikedPaladin/liteide)

**Comment by zenorocha** [comment]
That's super great @SpikedPaladin!

I just sent you an invite to join the Dracula org. Once you accept the invitation, you can transfer the repository and I'll add it to the website ;)

P.S.: @szaydel I just archived since it didn't have instructions and screenshot for a long time - https://github.com/dracula/liteide-archived

**Comment by zenorocha** [comment]
Aaaand it's live! https://draculatheme.com/liteide 🎉 🎉 🎉 

Feel free to share it with your friends and other LiteIDE enthusiasts!
