### ISSUE TITLE
TailwindCSS Plugin with Dracula Theme

### ISSUE THREAD

**Issue by nickgraffis** [dracula/dracula-theme#549]
## New Theme?

A package for adding Dracula color palette to tailwindcss project. [repository](https://github.com/nickgraffis/tailwind-dracula).

### What it does?

Allows use of tailwind utility classes with Dracula colors. Uses two naming options:
* Colors (pink, green, cyan, etc.)
* Vampires (nosferatu, dracula, buffy, etc.)

Use like so:
```
<div class="bg-pink"> //works!
 <p class="text-buffy"></p> //also works!
</div>
```

### Usage

You can add the plugin like so:
```
 plugins: [
    require('tailwind-dracula')(),
  ],
```
If you want to prefix the Dracula colors names to avoid clashes with common color classes
```
 plugins: [
    require('tailwind-dracula')('dracula'),
  ],
```

**Comment by zenorocha** [comment]
Hey @nickgraffis, that looks great! Congrats on building this plugin.

In order to add to the site, we need to follow some standards (https://github.com/dracula/template). For example, we always need a `screenshot.png` and `INSTALL.md` files in the root folder. Otherwise, the site won't be able to build.

If you can apply those patterns, I'll be able to add the repo to the site.

In any case, I already sent you the invitation to join the organization. Once you accept, you should be able to transfer the repository.

**Comment by nickgraffis** [comment]
Thanks @zenorocha transferred it over and added an INSTALL.md and a solid screenshot with an example.

Thanks a ton! Let me know if you need anything else.

**Comment by zenorocha** [comment]
And we're live! https://draculatheme.com/tailwind 🎉 🎉 🎉 

Congrats @nickgraffis on building this new theme.

Here are some important changes I made in order to follow the same standards as other repos inside this org: https://github.com/dracula/tailwind/commit/a95b92d925c5589cf407cbf00f3b338c02af819e

* Renamed repo from `tailwind-dracula` to `tailwind`. Package is still `tailwind-dracula` since that's easier to find on npm.
* Renamed branch from `main` to `master`. I know main is better, but all other repos should follow the same standard for the site to work as expected.
* Updated some URLs and made some tweaks to README.md and INSTALL.md so it better fits our site.

Cheers!

**Comment by nickgraffis** [comment]
Awesome! Looks great! Thanks a ton!!! 🙏🙏
