### ISSUE TITLE
Dracula for GtkSourceView

### ISSUE THREAD

**Issue by SpikedPaladin** [dracula/dracula-theme#566]
# Dracula for [GtkSourceView](https://wiki.gnome.org/Projects/GtkSourceView)

[dracula-gtksourceview](https://github.com/SpikedPaladin/dracula-gtksourceview)

Replace for https://github.com/dracula/gedit

-----
#### Gedit with Vala file
![Gedit with Vala](https://github.com/SpikedPaladin/dracula-gtksourceview/raw/master/screenshots/screenshot-vala.png)

#### Gnome Builder with C file
![Gnome builder with C](https://github.com/SpikedPaladin/dracula-gtksourceview/raw/master/screenshots/screenshot-c.png)

#### Gedit with Python file
![Gedit with Python](https://github.com/SpikedPaladin/dracula-gtksourceview/raw/master/screenshots/screenshot-python.png)

**Comment by bigpick** [comment]
Hey there  👋   Thanks for the work on the port!  The template repo looks mostly good, just had two notes.

One was that the links for the INSTALL/README usually point at the to-be-dracula ones (even though they'd be broken until then). Also, for the main README screenshot, the standard is to include a single `screenshot.png` in the root of the repo, and then just reference that, so maybe it'd be best if you pulled one of the ones out of the screenshots dir and switched to that?

---

As for the basis of the theme, I'm not sure I see it as a replacement of the gedit theme, but more so as a superset; I don't know if it'd be best that we make an additional repo for GtkSourceView and deprecate the gedit specific one, or to update the gedit one to include this work and change to GtkSourceView more generally and rename that repo, or some other third option.

Personally, I think the second option probably would make the most sense, since anyone in the future looking for GtkSourceView themes (builder, gedit, etc) will find the repo, and any existing links to the gedit one would be auto-updated to the new repo:

> We're happy to announce that starting today, we'll automatically redirect all requests for previous repository locations to their new home in these circumstances. There's nothing special you have to do. Just rename away and we'll take care of the rest.
