### ISSUE TITLE
New Theme for Node Console

### ISSUE THREAD

**Issue by brannonh** [dracula/dracula-theme#586]
New theme for use in Node `console.*` calls.

https://github.com/brannonh/dracula-console

<img src="https://github.com/brannonh/dracula-console/raw/master/screenshot.png" />

**Comment by bigpick** [comment]
Hey 👋   This looks nice. I think the choice of chalk is the best one if going the dependency route and not just escape codes, so looks good to me contents wise. 

Only thing I could _maybe_ think to add/change is to either:
1. Add one example of the `dracula.set('useBG'...)` in the sample code in the INSTALL page
2. ... Or just update the whole code block there to recreate the entire 3 block(s) that are shown in the main readme.

As for the template structure, everything looks good, but could you also update the "awesome contributors" link to point to the eventual Dracula repo for the theme, instead of the template dir? 

Thanks!

**Comment by brannonh** [comment]
@bigpick Thanks for the response! I'm behind on my notifications. 😊 Will update with your suggestions as soon as I have a few minutes.

**Comment by zenorocha** [comment]
I love this theme, I can't wait to start using it myself ;D

@brannonh I just sent you an invite to join the organization.

Once you accept it, you'll be able to transfer the repo and I'll take care of adding it to the site.

Thanks for building this! 🎉

And thanks @bigpick for helping with this!

**Comment by brannonh** [comment]
@zenorocha Thanks! I'm glad you like it. I accepted your invite. Looking forward to seeing it on the site! 😃

**Comment by zenorocha** [comment]
It's live on the site now: https://draculatheme.com/node-console

Thanks for building this @brandon-irs ;)

**Comment by zenorocha** [comment]
@brandon-irs can you please add me as an owner on npm too? `npm owner add zenorocha`

**Comment by brannonh** [comment]
@zenorocha Done!
