### ISSUE TITLE
New theme - Github

### ISSUE THREAD

**Issue by GlowingUmbreon** [dracula/dracula-theme#670]
![image](https://user-images.githubusercontent.com/37640997/148648177-06928638-b120-4036-bbd6-9fadbac7e181.png)
This theme requires use of the [stylus](https://add0n.com/stylus.html) extension. 

Source: https://github.com/GlowingUmbreon/dracula-github

**Comment by GlowingUmbreon** [comment]
The theme has changed slightly since the screenshot has been taken so it may look different now.

**Comment by zenorocha** [comment]
That's awesome @GlowingUmbreon, I can't wait to start using GitHub with Dracula colors.

I'm a little bit worried about keeping this theme updated since GitHub changes its stylesheet a lot, but I hope you can keep it up to date :)

In any case, I just sent you an invite to join the organization.

Once you accept it, you'll be able to transfer the repo and I'll take care of adding it to the site.

Thanks for building this! 🎉

**Comment by GlowingUmbreon** [comment]
> I'm a little bit worried about keeping this theme updated since GitHub changes its stylesheet a lot, but I hope you can keep it up to date :)

over 90% of the script is just :root variables, there are 3 other selectors one of which being a bug fix and the other two being a QOL thing.
Also I check github pretty much every day so if something breaks (unless its something I don't check often such as actions or something) I should notice.

**Comment by zenorocha** [comment]
That's great to hear, thanks a lot @GlowingUmbreon!

It's live now: https://draculatheme.com/github 🎉
