### ISSUE TITLE
Patchwork uses Dracula

### ISSUE THREAD

**Issue by 0verk1ll** [dracula/dracula-theme#710]
[Patchwork](https://github.com/ssbc/patchwork) includes the Dracula theme as an option. According to the README, the project has had its last release, so I don't know if you want to add the app to Dracula.

https://github.com/ssbc/patchwork/pull/1294 is the pull request where Dracula support was added.

Patchwork runs on GNU/Linux, MacOS, and Windows.

**Comment by zenorocha** [comment]
Hey @0verk1ll, that's great! I didn't know that Patchwork had a Dracula theme built in.

Since I'm not a Patchwork user I wouldn't be able to describe the installation instructions and how to activate the theme. However, you could do that and I can still add to the website, here's how...

You can create a new repo following this template: https://github.com/dracula/template
Just make sure you take a good screenshot, and add all the instructions in the `INSTALL.md` file. All pages on the draculatheme.com website use that file to be auto-generated.

Let me know if you have any questions.
