### ISSUE TITLE
New theme for Minecraft

### ISSUE THREAD

**Issue by Xetheon** [dracula/dracula-theme#730]
https://github.com/Xetheon/minecraft

This is a resourcepack for Minecraft that supports pretty much every version and uses a UI style I designed specifically to fit in line with Dracula simplicity. I think I've finally got it to a fully functioning state now am ready to submit it :D 

![screenshot](https://user-images.githubusercontent.com/62160456/176963299-9061efd7-f62e-4898-9138-6a1d82186dbe.png)

**Comment by zenorocha** [comment]
That's awesome @Xetheon, I love it!

I just moved the repository to the org and sent you an invite: https://github.com/dracula/minecraft
So feel free to remove the original repo: https://github.com/Xetheon/minecraft

In order to add this to the website, we need to include an `INSTALL.md` file. The website is auto-generated from all these types of files. You can use this as an example: https://github.com/dracula/template/blob/master/INSTALL.md

Two other things... can you regenerate the Releases and also rename these folders to "Dracula 1.19 - 1.9" instead of "Dracula UI ..."? Trying to avoid any confusion with https://draculatheme.com/ui

**Comment by luxonauta** [comment]
It's 🧟‍♂️ a-live: https://draculatheme.com/minecraft
