### ISSUE TITLE
Moving polymc theme to prismlauncher

### ISSUE THREAD

**Issue by Lutitious** [dracula/dracula-theme#761]
## Issue regarding polymc

Polymc was recently in a hostile takeover by the lead maintainer polymc. Most of the devs got together to create a for of polymc called prismlauncher. I would like to, as such move my polymc theme to prismlauncher but i am not sure on the protocol of how to do this. I would like some help for exactly how to since this is quite a unique situation. Documentationof the event is available [here](https://prismlauncher.org/wiki/overview/faq/)

**Comment by luxonauta** [comment]
Has the old theme for PolyMC stopped working? 🤔

If that's the case, the best thing is to remove it from the organization and create a new one for this new app.

**Comment by PoorPocketsMcNewHold** [comment]
[**@luxonauta**](https://github.com/luxonauta) commented on [Oct 21, 2022, 3:55 PM UTC](https://github.com/dracula/dracula-theme/issues/761#issuecomment-1287153179 "2022-10-21T15:55:55Z - Replied by Github Reply Comments"):
> Has the old theme for PolyMC stopped working? ![thinking](https://github.githubassets.com/images/icons/emoji/unicode/1f914.png)
> 
> If that's the case, the best thing is to remove it from the organization and create a new one for this new app.

It very likely haven't broken. OP just suggest changing the supported application to PrismLauncher, instead of PolyMC or MultiMC.
As explained accurately in the FAQ provided by OP,
MultiMC : Original Launcher. Was forked into PolyMC due to restrictive software license, preventing repackaging and distribution for other Linux platforms which would require other package format.
PolyMC : Was just recently forked into PrismLauncher due to political beliefs of repo owner, removing the code of conduct and removed previous maintainers from the project without prior consultation.

**Comment by Lutitious** [comment]
> Has the old theme for PolyMC stopped working? 🤔
> 
> If that's the case, the best thing is to remove it from the organization and create a new one for this new app.

Nope nothing is wrong with the theme itself its just polymc is no longer run by the original devs as explained in the prismlauncher faq, and switching to prismlauncher rather than polymc for the name would probably be a good idea since most of the devs for polymc are now working on prism instead

**Comment by luxonauta** [comment]
I understand, so we'd better create a new repository for this new app. Let's proceed in this way as if it were a new submission.
