### ISSUE TITLE
Change var or let color

### ISSUE THREAD

**Issue by AugustoPreis** [dracula/dracula-theme#769]
There's a way to change ```var``` or ```let``` color?

Currently, ```const``` have a purple color, but ```var``` and ```let``` has the same colors

I hant to know if is possible to change one of this two colors, like the following example

![var-let-const](https://user-images.githubusercontent.com/88676365/200043792-f4e1ac24-666e-4c48-97ba-197694b5e4b2.png)

**Comment by luxonauta** [comment]
Hi 🙋🏻‍♂️ Augusto, which app would you like this to change?

The ideal would be to create this Issue in its repository; ✅ here in this repository, we try to keep only questions about theme submissions, updates or suggestions for the organization.

It looks like this capture is done in VSCode; if that's the case, the best place for this Issue is [here](https://github.com/dracula/visual-studio-code).
