### ISSUE TITLE
Dracula for Polybar

### ISSUE THREAD

**Issue by matheusortiz** [dracula/dracula-theme#892]
## New Theme for Polybar

This is the link for the repository for Dracula Theme for Polybar:

[https://github.com/matheusortiz/dracula-polybar](https://github.com/matheusortiz/dracula-polybar)

Thank's

**Comment by Arszilla** [comment]
FYI, @luxonauta the repository is 404 - resulting in the file served in https://draculatheme.com/polybar to be missing.

**Comment by luxonauta** [comment]
Can you double-check, please? 🦇

**Comment by Arszilla** [comment]
Looks like the URL is fixed when you press the `Download ZIP file` in the `Details` section. However, the URL is still incorrect when clicking the URL found in `Install Manually`, which redirects to https://github.com/matheusortiz/dracula-polybar/archive/refs/heads/master.zip instead of https://github.com/dracula/polybar/archive/refs/heads/main.zip

**Comment by matheusortiz** [comment]
Sorry for the delay!

The INSTALL.md URL's have been fixed!
