### ISSUE TITLE
dracula/ggplot2 updates

### ISSUE THREAD

**Issue by jrdnbradford** [dracula/dracula-theme#915]
I recently completed a major update to [dracula/ggplot2](https://github.com/dracula/ggplot2) that includes changes to [INSTALL.md](https://github.com/dracula/ggplot2/blob/main/INSTALL.md) that need to be reflected on [draculatheme.com/ggplot2](https://draculatheme.com/ggplot2).

Relatedly, at some point I changed from branch `master` to `main` in the repo and some of the links on [draculatheme.com/ggplot2](https://draculatheme.com/ggplot2) (like "Edit this page") have a `404`.

Let me know if I can make these changes myself somewhere and put in a PR.

**Comment by luxonauta** [comment]
✅ Thanks, Jordan; I'll look at it and let you know soon!

**Comment by luxonauta** [comment]
Fixed in the last commit: https://github.com/dracula/draculatheme.com/commit/1a77566b7f1ba108b0690ee512b5c9fe5b9cc724; I added a route that should take the branches and add the default branch to the cache. So, the page now passes this parameter to the "wrapper". 🫡

🧟‍♂️ See: https://draculatheme.com/ggplot2

**Comment by jrdnbradford** [comment]
Awesome!!
