### ISSUE TITLE
Dracula Theme for Komorebi Tiling Window Manager

### ISSUE THREAD

**Issue by DamianK** [dracula/dracula-theme#962]
I have implemented Dracula Theme for Komorebi Tiling Window Manager.

Repository is here: https://github.com/DamianK/komorebi-dracula-theme

Regards,
Damian

**Comment by luxonauta** [comment]
Hi @saibulusu, we need to adjust a few things first to move forward, ok? ✨

First, we need to update the screenshot!

Can you take a single capture at the closest possible resolution to 1728x1117?

We also need a separate `.md` with installation instructions to show the theme on the site.

I ask for these changes to be standardized with the other repositories [see an example](https://github.com/dracula/notepad-plus-plus); this is also important because it helps other potential users who would like to contribute, too! 😁

- [Template](https://github.com/dracula/template)

Let me know if something isn't possible or if you have any questions! 🙂
