### ISSUE TITLE
Request for JetBrains Support in Dracula Pro 2

### ISSUE THREAD

**Issue by JediMan0308** [dracula/dracula-theme#965]
Dear Dracula Theme Team,
As a loyal user, I was excited about Dracula Pro 2 but disappointed to find it only supports JetBrains Fleet. Since I heavily rely on traditional JetBrains IDEs for work, I kindly request that you consider adding support for them in Dracula Pro 2.
Thank you for your consideration.

Best regards,
Vendy

**Comment by luxonauta** [comment]
Hi 👋🏻 Vendy,

We aim to offer support for all JetBrains IDEs, but we're not ready to release them due to prioritization and availability constraints. Therefore, we have decided to launch the package, in its version 2.0, with JetBrains Fleet & Legacy (for those we previously had with some critical fixes).

As with everything we do, this iteration is produced with the utmost care, and we want to continue adding value and growing our community.

**Comment by JediMan0308** [comment]
Thank you for the update. I appreciate your team's efforts and understand your current focus. I'll patiently await future support for other JetBrains IDEs. Looking forward to the upcoming 2.x releases!
